//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EConfiableBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Departamento
    {
        public string dep_codigo { get; set; }
        public string dep_nombre { get; set; }
        public string pai_codigo { get; set; }
    
        public virtual Pais Pais { get; set; }
    }
}
