//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EConfiableBD
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class EConfiableEntities : DbContext
    {
        public EConfiableEntities()
            : base("name=EConfiableEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Pais> Pais { get; set; }
        public virtual DbSet<Departamento> Departamento { get; set; }
        public virtual DbSet<Ciudad> Ciudad { get; set; }
        public virtual DbSet<TipoSociedad> TipoSociedad { get; set; }
        public virtual DbSet<Empresa> Empresa { get; set; }
        public virtual DbSet<TipoCategoriaMatricula> TipoCategoriaMatricula { get; set; }
        public virtual DbSet<TipoOrganizacion> TipoOrganizacion { get; set; }
    
        public virtual int Pais_Delete(string pai_codigo)
        {
            var pai_codigoParameter = pai_codigo != null ?
                new ObjectParameter("pai_codigo", pai_codigo) :
                new ObjectParameter("pai_codigo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Pais_Delete", pai_codigoParameter);
        }
    
        public virtual int Pais_Insert(string pai_codigo, string pai_nombre, string pai_codigointernacional, Nullable<bool> pai_predeterminado)
        {
            var pai_codigoParameter = pai_codigo != null ?
                new ObjectParameter("pai_codigo", pai_codigo) :
                new ObjectParameter("pai_codigo", typeof(string));
    
            var pai_nombreParameter = pai_nombre != null ?
                new ObjectParameter("pai_nombre", pai_nombre) :
                new ObjectParameter("pai_nombre", typeof(string));
    
            var pai_codigointernacionalParameter = pai_codigointernacional != null ?
                new ObjectParameter("pai_codigointernacional", pai_codigointernacional) :
                new ObjectParameter("pai_codigointernacional", typeof(string));
    
            var pai_predeterminadoParameter = pai_predeterminado.HasValue ?
                new ObjectParameter("pai_predeterminado", pai_predeterminado) :
                new ObjectParameter("pai_predeterminado", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Pais_Insert", pai_codigoParameter, pai_nombreParameter, pai_codigointernacionalParameter, pai_predeterminadoParameter);
        }
    
        public virtual ObjectResult<Pais_List_Result> Pais_List(string pai_codigo)
        {
            var pai_codigoParameter = pai_codigo != null ?
                new ObjectParameter("pai_codigo", pai_codigo) :
                new ObjectParameter("pai_codigo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Pais_List_Result>("Pais_List", pai_codigoParameter);
        }
    
        public virtual int Pais_Update(string pai_codigo, string pai_nombre, string pai_codigointernacional, Nullable<bool> pai_predeterminado)
        {
            var pai_codigoParameter = pai_codigo != null ?
                new ObjectParameter("pai_codigo", pai_codigo) :
                new ObjectParameter("pai_codigo", typeof(string));
    
            var pai_nombreParameter = pai_nombre != null ?
                new ObjectParameter("pai_nombre", pai_nombre) :
                new ObjectParameter("pai_nombre", typeof(string));
    
            var pai_codigointernacionalParameter = pai_codigointernacional != null ?
                new ObjectParameter("pai_codigointernacional", pai_codigointernacional) :
                new ObjectParameter("pai_codigointernacional", typeof(string));
    
            var pai_predeterminadoParameter = pai_predeterminado.HasValue ?
                new ObjectParameter("pai_predeterminado", pai_predeterminado) :
                new ObjectParameter("pai_predeterminado", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Pais_Update", pai_codigoParameter, pai_nombreParameter, pai_codigointernacionalParameter, pai_predeterminadoParameter);
        }
    
        public virtual int Departamento_Delete(string dep_codigo)
        {
            var dep_codigoParameter = dep_codigo != null ?
                new ObjectParameter("dep_codigo", dep_codigo) :
                new ObjectParameter("dep_codigo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Departamento_Delete", dep_codigoParameter);
        }
    
        public virtual int Departamento_Insert(string dep_codigo, string dep_nombre, string pai_codigo)
        {
            var dep_codigoParameter = dep_codigo != null ?
                new ObjectParameter("dep_codigo", dep_codigo) :
                new ObjectParameter("dep_codigo", typeof(string));
    
            var dep_nombreParameter = dep_nombre != null ?
                new ObjectParameter("dep_nombre", dep_nombre) :
                new ObjectParameter("dep_nombre", typeof(string));
    
            var pai_codigoParameter = pai_codigo != null ?
                new ObjectParameter("pai_codigo", pai_codigo) :
                new ObjectParameter("pai_codigo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Departamento_Insert", dep_codigoParameter, dep_nombreParameter, pai_codigoParameter);
        }
    
        public virtual ObjectResult<Departamento_List_Result> Departamento_List(string dep_codigo)
        {
            var dep_codigoParameter = dep_codigo != null ?
                new ObjectParameter("dep_codigo", dep_codigo) :
                new ObjectParameter("dep_codigo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Departamento_List_Result>("Departamento_List", dep_codigoParameter);
        }
    
        public virtual int Departamento_Update(string dep_codigo, string dep_nombre, string pai_codigo)
        {
            var dep_codigoParameter = dep_codigo != null ?
                new ObjectParameter("dep_codigo", dep_codigo) :
                new ObjectParameter("dep_codigo", typeof(string));
    
            var dep_nombreParameter = dep_nombre != null ?
                new ObjectParameter("dep_nombre", dep_nombre) :
                new ObjectParameter("dep_nombre", typeof(string));
    
            var pai_codigoParameter = pai_codigo != null ?
                new ObjectParameter("pai_codigo", pai_codigo) :
                new ObjectParameter("pai_codigo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Departamento_Update", dep_codigoParameter, dep_nombreParameter, pai_codigoParameter);
        }
    
        public virtual int Ciudad_Delete(string ciu_codigo)
        {
            var ciu_codigoParameter = ciu_codigo != null ?
                new ObjectParameter("ciu_codigo", ciu_codigo) :
                new ObjectParameter("ciu_codigo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Ciudad_Delete", ciu_codigoParameter);
        }
    
        public virtual int Ciudad_Insert(string ciu_codigo, string ciu_nombre, Nullable<bool> ciu_predeterminado, Nullable<double> ciu_longitud, Nullable<double> ciu_latitud, string dep_codigo)
        {
            var ciu_codigoParameter = ciu_codigo != null ?
                new ObjectParameter("ciu_codigo", ciu_codigo) :
                new ObjectParameter("ciu_codigo", typeof(string));
    
            var ciu_nombreParameter = ciu_nombre != null ?
                new ObjectParameter("ciu_nombre", ciu_nombre) :
                new ObjectParameter("ciu_nombre", typeof(string));
    
            var ciu_predeterminadoParameter = ciu_predeterminado.HasValue ?
                new ObjectParameter("ciu_predeterminado", ciu_predeterminado) :
                new ObjectParameter("ciu_predeterminado", typeof(bool));
    
            var ciu_longitudParameter = ciu_longitud.HasValue ?
                new ObjectParameter("ciu_longitud", ciu_longitud) :
                new ObjectParameter("ciu_longitud", typeof(double));
    
            var ciu_latitudParameter = ciu_latitud.HasValue ?
                new ObjectParameter("ciu_latitud", ciu_latitud) :
                new ObjectParameter("ciu_latitud", typeof(double));
    
            var dep_codigoParameter = dep_codigo != null ?
                new ObjectParameter("dep_codigo", dep_codigo) :
                new ObjectParameter("dep_codigo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Ciudad_Insert", ciu_codigoParameter, ciu_nombreParameter, ciu_predeterminadoParameter, ciu_longitudParameter, ciu_latitudParameter, dep_codigoParameter);
        }
    
        public virtual ObjectResult<Ciudad_List_Result> Ciudad_List(string ciu_codigo)
        {
            var ciu_codigoParameter = ciu_codigo != null ?
                new ObjectParameter("ciu_codigo", ciu_codigo) :
                new ObjectParameter("ciu_codigo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Ciudad_List_Result>("Ciudad_List", ciu_codigoParameter);
        }
    
        public virtual int Ciudad_Update(string ciu_codigo, string ciu_nombre, Nullable<bool> ciu_predeterminado, Nullable<double> ciu_longitud, Nullable<double> ciu_latitud, string dep_codigo)
        {
            var ciu_codigoParameter = ciu_codigo != null ?
                new ObjectParameter("ciu_codigo", ciu_codigo) :
                new ObjectParameter("ciu_codigo", typeof(string));
    
            var ciu_nombreParameter = ciu_nombre != null ?
                new ObjectParameter("ciu_nombre", ciu_nombre) :
                new ObjectParameter("ciu_nombre", typeof(string));
    
            var ciu_predeterminadoParameter = ciu_predeterminado.HasValue ?
                new ObjectParameter("ciu_predeterminado", ciu_predeterminado) :
                new ObjectParameter("ciu_predeterminado", typeof(bool));
    
            var ciu_longitudParameter = ciu_longitud.HasValue ?
                new ObjectParameter("ciu_longitud", ciu_longitud) :
                new ObjectParameter("ciu_longitud", typeof(double));
    
            var ciu_latitudParameter = ciu_latitud.HasValue ?
                new ObjectParameter("ciu_latitud", ciu_latitud) :
                new ObjectParameter("ciu_latitud", typeof(double));
    
            var dep_codigoParameter = dep_codigo != null ?
                new ObjectParameter("dep_codigo", dep_codigo) :
                new ObjectParameter("dep_codigo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Ciudad_Update", ciu_codigoParameter, ciu_nombreParameter, ciu_predeterminadoParameter, ciu_longitudParameter, ciu_latitudParameter, dep_codigoParameter);
        }
    
        public virtual int Tiposociedad_Delete(Nullable<int> tso_id)
        {
            var tso_idParameter = tso_id.HasValue ?
                new ObjectParameter("tso_id", tso_id) :
                new ObjectParameter("tso_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Tiposociedad_Delete", tso_idParameter);
        }
    
        public virtual int Tiposociedad_Insert(string tso_descripcion)
        {
            var tso_descripcionParameter = tso_descripcion != null ?
                new ObjectParameter("tso_descripcion", tso_descripcion) :
                new ObjectParameter("tso_descripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Tiposociedad_Insert", tso_descripcionParameter);
        }
    
        public virtual ObjectResult<Tiposociedad_List_Result> Tiposociedad_List(Nullable<int> tso_id)
        {
            var tso_idParameter = tso_id.HasValue ?
                new ObjectParameter("tso_id", tso_id) :
                new ObjectParameter("tso_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Tiposociedad_List_Result>("Tiposociedad_List", tso_idParameter);
        }
    
        public virtual int Tiposociedad_Update(Nullable<int> tso_id, string tso_descripcion)
        {
            var tso_idParameter = tso_id.HasValue ?
                new ObjectParameter("tso_id", tso_id) :
                new ObjectParameter("tso_id", typeof(int));
    
            var tso_descripcionParameter = tso_descripcion != null ?
                new ObjectParameter("tso_descripcion", tso_descripcion) :
                new ObjectParameter("tso_descripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Tiposociedad_Update", tso_idParameter, tso_descripcionParameter);
        }
    
        public virtual int Empresa_Delete(Nullable<int> emp_id)
        {
            var emp_idParameter = emp_id.HasValue ?
                new ObjectParameter("emp_id", emp_id) :
                new ObjectParameter("emp_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Empresa_Delete", emp_idParameter);
        }
    
        public virtual int Empresa_Insert(string emp_nit, Nullable<int> emp_digverificacion, string emp_nombre, string emp_direccion, string ciu_codigo, string emp_telefonos, string emp_email, string emp_url, string emp_logotipo, Nullable<double> emp_longitud, Nullable<double> emp_latitud, string emp_nummatricula, Nullable<System.DateTime> emp_fechamatricula, Nullable<System.DateTime> emp_fecharenovacion, Nullable<System.DateTime> emp_fechacancelacion, Nullable<System.DateTime> emp_fechavigencia, Nullable<int> emp_ultanorenovado, string emp_rup, string emp_runeol, string emp_rut, Nullable<int> tso_id, Nullable<int> tor_id, Nullable<int> tcm_id, Nullable<int> emp_numeroempleados, Nullable<bool> emp_afiliadocamcomercio, Nullable<bool> emp_activa)
        {
            var emp_nitParameter = emp_nit != null ?
                new ObjectParameter("emp_nit", emp_nit) :
                new ObjectParameter("emp_nit", typeof(string));
    
            var emp_digverificacionParameter = emp_digverificacion.HasValue ?
                new ObjectParameter("emp_digverificacion", emp_digverificacion) :
                new ObjectParameter("emp_digverificacion", typeof(int));
    
            var emp_nombreParameter = emp_nombre != null ?
                new ObjectParameter("emp_nombre", emp_nombre) :
                new ObjectParameter("emp_nombre", typeof(string));
    
            var emp_direccionParameter = emp_direccion != null ?
                new ObjectParameter("emp_direccion", emp_direccion) :
                new ObjectParameter("emp_direccion", typeof(string));
    
            var ciu_codigoParameter = ciu_codigo != null ?
                new ObjectParameter("ciu_codigo", ciu_codigo) :
                new ObjectParameter("ciu_codigo", typeof(string));
    
            var emp_telefonosParameter = emp_telefonos != null ?
                new ObjectParameter("emp_telefonos", emp_telefonos) :
                new ObjectParameter("emp_telefonos", typeof(string));
    
            var emp_emailParameter = emp_email != null ?
                new ObjectParameter("emp_email", emp_email) :
                new ObjectParameter("emp_email", typeof(string));
    
            var emp_urlParameter = emp_url != null ?
                new ObjectParameter("emp_url", emp_url) :
                new ObjectParameter("emp_url", typeof(string));
    
            var emp_logotipoParameter = emp_logotipo != null ?
                new ObjectParameter("emp_logotipo", emp_logotipo) :
                new ObjectParameter("emp_logotipo", typeof(string));
    
            var emp_longitudParameter = emp_longitud.HasValue ?
                new ObjectParameter("emp_longitud", emp_longitud) :
                new ObjectParameter("emp_longitud", typeof(double));
    
            var emp_latitudParameter = emp_latitud.HasValue ?
                new ObjectParameter("emp_latitud", emp_latitud) :
                new ObjectParameter("emp_latitud", typeof(double));
    
            var emp_nummatriculaParameter = emp_nummatricula != null ?
                new ObjectParameter("emp_nummatricula", emp_nummatricula) :
                new ObjectParameter("emp_nummatricula", typeof(string));
    
            var emp_fechamatriculaParameter = emp_fechamatricula.HasValue ?
                new ObjectParameter("emp_fechamatricula", emp_fechamatricula) :
                new ObjectParameter("emp_fechamatricula", typeof(System.DateTime));
    
            var emp_fecharenovacionParameter = emp_fecharenovacion.HasValue ?
                new ObjectParameter("emp_fecharenovacion", emp_fecharenovacion) :
                new ObjectParameter("emp_fecharenovacion", typeof(System.DateTime));
    
            var emp_fechacancelacionParameter = emp_fechacancelacion.HasValue ?
                new ObjectParameter("emp_fechacancelacion", emp_fechacancelacion) :
                new ObjectParameter("emp_fechacancelacion", typeof(System.DateTime));
    
            var emp_fechavigenciaParameter = emp_fechavigencia.HasValue ?
                new ObjectParameter("emp_fechavigencia", emp_fechavigencia) :
                new ObjectParameter("emp_fechavigencia", typeof(System.DateTime));
    
            var emp_ultanorenovadoParameter = emp_ultanorenovado.HasValue ?
                new ObjectParameter("emp_ultanorenovado", emp_ultanorenovado) :
                new ObjectParameter("emp_ultanorenovado", typeof(int));
    
            var emp_rupParameter = emp_rup != null ?
                new ObjectParameter("emp_rup", emp_rup) :
                new ObjectParameter("emp_rup", typeof(string));
    
            var emp_runeolParameter = emp_runeol != null ?
                new ObjectParameter("emp_runeol", emp_runeol) :
                new ObjectParameter("emp_runeol", typeof(string));
    
            var emp_rutParameter = emp_rut != null ?
                new ObjectParameter("emp_rut", emp_rut) :
                new ObjectParameter("emp_rut", typeof(string));
    
            var tso_idParameter = tso_id.HasValue ?
                new ObjectParameter("tso_id", tso_id) :
                new ObjectParameter("tso_id", typeof(int));
    
            var tor_idParameter = tor_id.HasValue ?
                new ObjectParameter("tor_id", tor_id) :
                new ObjectParameter("tor_id", typeof(int));
    
            var tcm_idParameter = tcm_id.HasValue ?
                new ObjectParameter("tcm_id", tcm_id) :
                new ObjectParameter("tcm_id", typeof(int));
    
            var emp_numeroempleadosParameter = emp_numeroempleados.HasValue ?
                new ObjectParameter("emp_numeroempleados", emp_numeroempleados) :
                new ObjectParameter("emp_numeroempleados", typeof(int));
    
            var emp_afiliadocamcomercioParameter = emp_afiliadocamcomercio.HasValue ?
                new ObjectParameter("emp_afiliadocamcomercio", emp_afiliadocamcomercio) :
                new ObjectParameter("emp_afiliadocamcomercio", typeof(bool));
    
            var emp_activaParameter = emp_activa.HasValue ?
                new ObjectParameter("emp_activa", emp_activa) :
                new ObjectParameter("emp_activa", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Empresa_Insert", emp_nitParameter, emp_digverificacionParameter, emp_nombreParameter, emp_direccionParameter, ciu_codigoParameter, emp_telefonosParameter, emp_emailParameter, emp_urlParameter, emp_logotipoParameter, emp_longitudParameter, emp_latitudParameter, emp_nummatriculaParameter, emp_fechamatriculaParameter, emp_fecharenovacionParameter, emp_fechacancelacionParameter, emp_fechavigenciaParameter, emp_ultanorenovadoParameter, emp_rupParameter, emp_runeolParameter, emp_rutParameter, tso_idParameter, tor_idParameter, tcm_idParameter, emp_numeroempleadosParameter, emp_afiliadocamcomercioParameter, emp_activaParameter);
        }
    
        public virtual ObjectResult<Empresa_List_Result> Empresa_List(Nullable<int> emp_id)
        {
            var emp_idParameter = emp_id.HasValue ?
                new ObjectParameter("emp_id", emp_id) :
                new ObjectParameter("emp_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Empresa_List_Result>("Empresa_List", emp_idParameter);
        }
    
        public virtual int Empresa_Update(Nullable<int> emp_id, string emp_nit, Nullable<int> emp_digverificacion, string emp_nombre, string emp_direccion, string ciu_codigo, string emp_telefonos, string emp_email, string emp_url, string emp_logotipo, Nullable<double> emp_longitud, Nullable<double> emp_latitud, string emp_nummatricula, Nullable<System.DateTime> emp_fechamatricula, Nullable<System.DateTime> emp_fecharenovacion, Nullable<System.DateTime> emp_fechacancelacion, Nullable<System.DateTime> emp_fechavigencia, Nullable<int> emp_ultanorenovado, string emp_rup, string emp_runeol, string emp_rut, Nullable<int> tso_id, Nullable<int> tor_id, Nullable<int> tcm_id, Nullable<int> emp_numeroempleados, Nullable<bool> emp_afiliadocamcomercio, Nullable<bool> emp_activa)
        {
            var emp_idParameter = emp_id.HasValue ?
                new ObjectParameter("emp_id", emp_id) :
                new ObjectParameter("emp_id", typeof(int));
    
            var emp_nitParameter = emp_nit != null ?
                new ObjectParameter("emp_nit", emp_nit) :
                new ObjectParameter("emp_nit", typeof(string));
    
            var emp_digverificacionParameter = emp_digverificacion.HasValue ?
                new ObjectParameter("emp_digverificacion", emp_digverificacion) :
                new ObjectParameter("emp_digverificacion", typeof(int));
    
            var emp_nombreParameter = emp_nombre != null ?
                new ObjectParameter("emp_nombre", emp_nombre) :
                new ObjectParameter("emp_nombre", typeof(string));
    
            var emp_direccionParameter = emp_direccion != null ?
                new ObjectParameter("emp_direccion", emp_direccion) :
                new ObjectParameter("emp_direccion", typeof(string));
    
            var ciu_codigoParameter = ciu_codigo != null ?
                new ObjectParameter("ciu_codigo", ciu_codigo) :
                new ObjectParameter("ciu_codigo", typeof(string));
    
            var emp_telefonosParameter = emp_telefonos != null ?
                new ObjectParameter("emp_telefonos", emp_telefonos) :
                new ObjectParameter("emp_telefonos", typeof(string));
    
            var emp_emailParameter = emp_email != null ?
                new ObjectParameter("emp_email", emp_email) :
                new ObjectParameter("emp_email", typeof(string));
    
            var emp_urlParameter = emp_url != null ?
                new ObjectParameter("emp_url", emp_url) :
                new ObjectParameter("emp_url", typeof(string));
    
            var emp_logotipoParameter = emp_logotipo != null ?
                new ObjectParameter("emp_logotipo", emp_logotipo) :
                new ObjectParameter("emp_logotipo", typeof(string));
    
            var emp_longitudParameter = emp_longitud.HasValue ?
                new ObjectParameter("emp_longitud", emp_longitud) :
                new ObjectParameter("emp_longitud", typeof(double));
    
            var emp_latitudParameter = emp_latitud.HasValue ?
                new ObjectParameter("emp_latitud", emp_latitud) :
                new ObjectParameter("emp_latitud", typeof(double));
    
            var emp_nummatriculaParameter = emp_nummatricula != null ?
                new ObjectParameter("emp_nummatricula", emp_nummatricula) :
                new ObjectParameter("emp_nummatricula", typeof(string));
    
            var emp_fechamatriculaParameter = emp_fechamatricula.HasValue ?
                new ObjectParameter("emp_fechamatricula", emp_fechamatricula) :
                new ObjectParameter("emp_fechamatricula", typeof(System.DateTime));
    
            var emp_fecharenovacionParameter = emp_fecharenovacion.HasValue ?
                new ObjectParameter("emp_fecharenovacion", emp_fecharenovacion) :
                new ObjectParameter("emp_fecharenovacion", typeof(System.DateTime));
    
            var emp_fechacancelacionParameter = emp_fechacancelacion.HasValue ?
                new ObjectParameter("emp_fechacancelacion", emp_fechacancelacion) :
                new ObjectParameter("emp_fechacancelacion", typeof(System.DateTime));
    
            var emp_fechavigenciaParameter = emp_fechavigencia.HasValue ?
                new ObjectParameter("emp_fechavigencia", emp_fechavigencia) :
                new ObjectParameter("emp_fechavigencia", typeof(System.DateTime));
    
            var emp_ultanorenovadoParameter = emp_ultanorenovado.HasValue ?
                new ObjectParameter("emp_ultanorenovado", emp_ultanorenovado) :
                new ObjectParameter("emp_ultanorenovado", typeof(int));
    
            var emp_rupParameter = emp_rup != null ?
                new ObjectParameter("emp_rup", emp_rup) :
                new ObjectParameter("emp_rup", typeof(string));
    
            var emp_runeolParameter = emp_runeol != null ?
                new ObjectParameter("emp_runeol", emp_runeol) :
                new ObjectParameter("emp_runeol", typeof(string));
    
            var emp_rutParameter = emp_rut != null ?
                new ObjectParameter("emp_rut", emp_rut) :
                new ObjectParameter("emp_rut", typeof(string));
    
            var tso_idParameter = tso_id.HasValue ?
                new ObjectParameter("tso_id", tso_id) :
                new ObjectParameter("tso_id", typeof(int));
    
            var tor_idParameter = tor_id.HasValue ?
                new ObjectParameter("tor_id", tor_id) :
                new ObjectParameter("tor_id", typeof(int));
    
            var tcm_idParameter = tcm_id.HasValue ?
                new ObjectParameter("tcm_id", tcm_id) :
                new ObjectParameter("tcm_id", typeof(int));
    
            var emp_numeroempleadosParameter = emp_numeroempleados.HasValue ?
                new ObjectParameter("emp_numeroempleados", emp_numeroempleados) :
                new ObjectParameter("emp_numeroempleados", typeof(int));
    
            var emp_afiliadocamcomercioParameter = emp_afiliadocamcomercio.HasValue ?
                new ObjectParameter("emp_afiliadocamcomercio", emp_afiliadocamcomercio) :
                new ObjectParameter("emp_afiliadocamcomercio", typeof(bool));
    
            var emp_activaParameter = emp_activa.HasValue ?
                new ObjectParameter("emp_activa", emp_activa) :
                new ObjectParameter("emp_activa", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Empresa_Update", emp_idParameter, emp_nitParameter, emp_digverificacionParameter, emp_nombreParameter, emp_direccionParameter, ciu_codigoParameter, emp_telefonosParameter, emp_emailParameter, emp_urlParameter, emp_logotipoParameter, emp_longitudParameter, emp_latitudParameter, emp_nummatriculaParameter, emp_fechamatriculaParameter, emp_fecharenovacionParameter, emp_fechacancelacionParameter, emp_fechavigenciaParameter, emp_ultanorenovadoParameter, emp_rupParameter, emp_runeolParameter, emp_rutParameter, tso_idParameter, tor_idParameter, tcm_idParameter, emp_numeroempleadosParameter, emp_afiliadocamcomercioParameter, emp_activaParameter);
        }
    
        public virtual int Tipocategoriamatricula_Delete(Nullable<int> tcm_id)
        {
            var tcm_idParameter = tcm_id.HasValue ?
                new ObjectParameter("tcm_id", tcm_id) :
                new ObjectParameter("tcm_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Tipocategoriamatricula_Delete", tcm_idParameter);
        }
    
        public virtual int Tipocategoriamatricula_Insert(string tcm_descripcion)
        {
            var tcm_descripcionParameter = tcm_descripcion != null ?
                new ObjectParameter("tcm_descripcion", tcm_descripcion) :
                new ObjectParameter("tcm_descripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Tipocategoriamatricula_Insert", tcm_descripcionParameter);
        }
    
        public virtual ObjectResult<Tipocategoriamatricula_List_Result> Tipocategoriamatricula_List(Nullable<int> tcm_id)
        {
            var tcm_idParameter = tcm_id.HasValue ?
                new ObjectParameter("tcm_id", tcm_id) :
                new ObjectParameter("tcm_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Tipocategoriamatricula_List_Result>("Tipocategoriamatricula_List", tcm_idParameter);
        }
    
        public virtual int Tipocategoriamatricula_Update(Nullable<int> tcm_id, string tcm_descripcion)
        {
            var tcm_idParameter = tcm_id.HasValue ?
                new ObjectParameter("tcm_id", tcm_id) :
                new ObjectParameter("tcm_id", typeof(int));
    
            var tcm_descripcionParameter = tcm_descripcion != null ?
                new ObjectParameter("tcm_descripcion", tcm_descripcion) :
                new ObjectParameter("tcm_descripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Tipocategoriamatricula_Update", tcm_idParameter, tcm_descripcionParameter);
        }
    
        public virtual int Tipoorganizacion_Delete(Nullable<int> tor_id)
        {
            var tor_idParameter = tor_id.HasValue ?
                new ObjectParameter("tor_id", tor_id) :
                new ObjectParameter("tor_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Tipoorganizacion_Delete", tor_idParameter);
        }
    
        public virtual int Tipoorganizacion_Insert(string tor_descripcion)
        {
            var tor_descripcionParameter = tor_descripcion != null ?
                new ObjectParameter("tor_descripcion", tor_descripcion) :
                new ObjectParameter("tor_descripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Tipoorganizacion_Insert", tor_descripcionParameter);
        }
    
        public virtual ObjectResult<Tipoorganizacion_List_Result> Tipoorganizacion_List(Nullable<int> tor_id)
        {
            var tor_idParameter = tor_id.HasValue ?
                new ObjectParameter("tor_id", tor_id) :
                new ObjectParameter("tor_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Tipoorganizacion_List_Result>("Tipoorganizacion_List", tor_idParameter);
        }
    
        public virtual int Tipoorganizacion_Update(Nullable<int> tor_id, string tor_descripcion)
        {
            var tor_idParameter = tor_id.HasValue ?
                new ObjectParameter("tor_id", tor_id) :
                new ObjectParameter("tor_id", typeof(int));
    
            var tor_descripcionParameter = tor_descripcion != null ?
                new ObjectParameter("tor_descripcion", tor_descripcion) :
                new ObjectParameter("tor_descripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Tipoorganizacion_Update", tor_idParameter, tor_descripcionParameter);
        }
    }
}
